### ISSUE TITLE
hg38 support?

### ISSUE THREAD

**Issue by pdiakumis** [vanallenlab/moalmanac#2]
Thanks for this nice tool @brendanreardon!
Before I dig in, I've noticed in the docs:

> This method currently geared towards hg19/b37 reference files

Is hg38 currently supported? I'm guessing majority of bioinfo folks would be on hg38 by now.

Cheers,
Peter

**Comment by brendanreardon** [comment]
Hi Peter,

Thank you for the compliment! For better or for worse, we don't have hg38 properly supported yet. It is on the to do list, albeit it is low on our priorities. All external datasources should have hg38 versions so those just need to be downloaded and formatted with the scripts contained in this repository. For our database, transcripts and genes would need to be remapped. We'll try to bump this up on the priorities since there is interest! Thank you for reaching out.
